apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: merka-store-cnpg-barman
  namespace: cnpg
spec:
  configuration:
    destinationPath: "s3://merka-cloud-store/cnpg-barman/"
    endpointURL: "http://merka-master:3900"
    s3Credentials:
      accessKeyId:
        name: garage-bark1
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-bark1
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
