# Instructions from https://cloudnative-pg.io/documentation/current/quickstart/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg1
  namespace: cnpg
spec:
  instances: 2
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: merka-store-cnpg-barman
  storage:
    size: 1Gi